export const SPECIALTY_OPTIONS = [
  'Preparo do reboco (Limpeza, Lixa, Selador/Fundo Preparador)',
  'Preparo do Acartonado (Lixa e Fundo Preparador)',
  'Massa Corrida (Aplicação e lixamento)',
  'Massa Acrílica (Aplicação e lixamento)',
  'Tintas Acrílicas',
  'Tintas Solvente',
  'Pinturas em Metais (Tratamento especial)',
  'Pinturas em Madeira (Tratamento especial)',
  'Pinturas com Efeitos',
  'Texturas',
  'Airless',
  'Pistolas Industriais (Pinturas, Texturas e Efeitos)',
  'Lixadeiras: pequenas, médias e de grande porte',
  'Compressores de pequenos, médios e de grande porte',
  'Reformas (tratamento de patologias e superfícies)',
  'Acabamentos Finos',
  'NR-35 (trabalho em altura)',
  'EPIs'
] as const;
